Repository ophrescue/RescueRails, pull requests merged in 2018-04, with the labels that each got.

#739 updated amazon wishlist url
  app/views/pages/other_ways_to_give.html.erb
Labels: in progress

#681 Adoption Coordinators Should be Able to Edit References
  app/assets/javascripts/adoption_form.js
  app/assets/stylesheets/custom.scss
  app/controllers/adopters_controller.rb
  app/controllers/password_resets_controller.rb
  app/models/adopter.rb
  app/models/reference.rb
  app/views/adopters/_adopter_references.html.erb
  app/views/adopters/show.html.erb
  app/views/audited/audits/_audit.html.erb
  app/views/references/_reference.html.erb
  spec/factories/reference.rb
  spec/features/apply_to_adopt_spec.rb
  spec/features/edit_reference_spec.rb
  spec/rails_helper.rb
Labels: code reivew

#743 Bootstrap upgrade to 2.3.2
  app/assets/javascripts/application.js
  app/assets/stylesheets/custom.scss
  vendor/assets/images/glyphicons-halflings-white.png
  vendor/assets/images/glyphicons-halflings.png
  vendor/assets/javascripts/bootstrap.js
  vendor/assets/javascripts/twitter/bootstrap.js
  vendor/assets/javascripts/twitter/bootstrap/affix.js
  vendor/assets/javascripts/twitter/bootstrap/alert.js
  vendor/assets/javascripts/twitter/bootstrap/button.js
  vendor/assets/javascripts/twitter/bootstrap/carousel.js
  vendor/assets/javascripts/twitter/bootstrap/collapse.js
  vendor/assets/javascripts/twitter/bootstrap/dropdown.js
  vendor/assets/javascripts/twitter/bootstrap/modal.js
  vendor/assets/javascripts/twitter/bootstrap/popover.js
  vendor/assets/javascripts/twitter/bootstrap/scrollspy.js
  vendor/assets/javascripts/twitter/bootstrap/tab.js
  vendor/assets/javascripts/twitter/bootstrap/tooltip.js
  vendor/assets/javascripts/twitter/bootstrap/transition.js
  vendor/assets/javascripts/twitter/bootstrap/typeahead.js
  vendor/assets/stylesheets/bootstrap-responsive.scss
  vendor/assets/stylesheets/bootstrap.scss
Labels: in progress

#746 Training Partner Page
  app/views/layouts/_topbar.html.erb
  app/views/pages/training_partners.html.erb
  config/routes.rb
  public/docs/free_training_coupon.jpg
Labels: in progress

#747 rcs logo update
  app/assets/images/sponsors/rayscanineservices.png
  app/views/pages/community_partners.html.erb
Labels: in progress

#748 training partner page update
  app/assets/images/sponsors/walkingwithafriend.png
  app/views/pages/training_partners.html.erb
Labels: in progress

#749 Training page add mindy contact info
  app/mailers/training_mailer.rb
  app/views/pages/training_partners.html.erb
Labels: code review

#763 Revert "Removes unicorn in favor of puma"
  Gemfile
Labels: code review

#751 Feature/rails 52
  Gemfile
  Gemfile.lock
  app/models/dog.rb
  app/models/dog_searcher.rb
  app/views/dogs/_manager.html.erb
  app/views/sessions/new.html.erb
  config/initializers/secret_token.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/adopters_controller_spec.rb
  spec/controllers/comments_controller_spec.rb
  spec/controllers/dogs_controller_spec.rb
  spec/controllers/events_controller_spec.rb
  spec/controllers/folders_controller_spec.rb
  spec/controllers/password_resets_controller_spec.rb
  spec/controllers/shelters_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/breed.rb
  spec/factories/dog.rb
  spec/features/apply_to_adopt_spec.rb
  spec/features/edit_adopter_spec.rb
  spec/features/edit_reference_spec.rb
  spec/features/event_management_spec.rb
  spec/features/manage_dogs_spec.rb
  spec/features/manage_medical_behavior_summaries_spec.rb
  spec/features/user_signin_spec.rb
  spec/models/dog_spec.rb
Labels: code review
